name: Deploy Zoner docs to /docs/Zoner on org site

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Zoner
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Moonwave
        run: |
          npm i -g moonwave
          moonwave build   # outputs ./build

      - name: Checkout org site (container)
        uses: actions/checkout@v4
        with:
          repository: skyriverstudios/skyriverstudios.github.io
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          path: site

      - name: Copy build into /docs/Zoner
        run: |
          mkdir -p site/docs/Zoner
          rm -rf site/docs/Zoner/*
          cp -a build/. site/docs/Zoner/
          touch site/.nojekyll

      - name: Commit & push changes
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Deploy Zoner docs from $GITHUB_SHA"
            git push
          fi
